config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "pages#home"

  resources :ski_resorts, only: [:index, :show] do
    resources :check_ins, only: [:create]
    resources :snow_reports, only: [:create]
  end

  resources :check_ins, only: [:update] do
    resources :reviews, only: [:create]
    # resources :snow_reports, only: [:create]
    # resources :reviews, only: [:create]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_map.html.erb
<div style="<%=style%> "
   data-map-target="map"
  <% unless current_page?(controller: 'ski_resorts', action: 'index')%>
    data-map-resort-info-value='true'
  <% end  %>
  >
</div>

app/views/shared/_navbar.html.erb
<div class="nav-bar d-flex">
  <div class="search">
    <%= link_to ski_resorts_path, class: "nav-link" do %>
      <i class="fa-solid fa-magnifying-glass" style="color: #2d5c9e;"></i>
    <% end %>
  </div>
  <div class="home">
    <% if user_signed_in? && current_user.check_ins.last && current_user.check_ins&.last.checked_out_at.nil? %>
      <%= link_to ski_resort_path(current_user.check_ins.last.ski_resort), class: "navbar-brand" do %>
        <i class="fa-solid fa-house"style="color: #2d5c9e;"></i>
      <% end %>
    <% else %>
      <%= link_to root_path, class: "navbar-brand" do %>
         <i class="fa-solid fa-house"style="color: #2d5c9e;"></i>
      <% end %>
    <% end %>
  </div>
  <div class="profile">
    <% if user_signed_in? %>
      <div class="nav-item dropdown">
        <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa-solid fa-user" style="color: #2d5c9e;" class="avatar", alt="dropdown menu"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" do %>
            <i class="fa-solid fa-user" style="color: #2d5c9e;"></i>
          <% end %>
        </div>
      </div>
    <% else %>
      <div class="nav-item">
        <%= link_to new_user_session_path, class: "nav-link" do %>
          <i class="fa-solid fa-user" style="color: #2d5c9e;"></i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar_wider.html.erb
<div class="nav-bar d-flex wider">
  <div class="search">
    <%= link_to ski_resorts_path, class: "nav-link" do %>
      <i class="fa-solid fa-magnifying-glass" style="color: #2d5c9e;"></i>
    <% end %>
  </div>
  <div class="home">
    <% if user_signed_in? && current_user.check_ins.last && current_user.check_ins&.last.checked_out_at.nil? %>
      <%= link_to ski_resort_path(current_user.check_ins.last.ski_resort), class: "navbar-brand" do %>
        <i class="fa-solid fa-house"style="color: #2d5c9e;"></i>
      <% end %>
    <% else %>
      <%= link_to root_path, class: "navbar-brand" do %>
         <i class="fa-solid fa-house"style="color: #2d5c9e;"></i>
      <% end %>
    <% end %>
  </div>
  <div class="profile">
    <% if user_signed_in? %>
      <div class="nav-item dropdown">
        <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa-solid fa-user" style="color: #2d5c9e;" class="avatar", alt="dropdown menu"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" do %>
            <i class="fa-solid fa-user" style="color: #2d5c9e;"></i>
          <% end %>
        </div>
      </div>
    <% else %>
      <div class="nav-item">
        <%= link_to new_user_session_path, class: "nav-link" do %>
          <i class="fa-solid fa-user" style="color: #2d5c9e;"></i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_snow_cond_icon.html.erb
<% if ski_resort.current_condition == 'no_snow' %>
<%=   image_tag 'clear.svg', alt: 'No snow', class: 'svg-icon-small nosnow', width: size, height: size %>
<% elsif ski_resort.current_condition == 'slushy' %>
 <%= image_tag 'slush.svg', alt: 'No snow', class: 'svg-icon-small nosnow', width: size, height: size %>
<% elsif ski_resort.current_condition == 'icy' %>
<%=   image_tag 'icy.svg', alt: 'No snow', class: 'svg-icon-small nosnow', width: size, height: size %>
<% elsif ski_resort.current_condition == 'groomed_snow' %>
<%=   image_tag 'groomed.svg', alt: 'No snow', class: 'svg-icon-small nosnow', width: size, height: size %>
<% elsif ski_resort.current_condition == 'packed_powder' %>
<%=   image_tag 'packed.svg', alt: 'No snow', class: 'svg-icon-small nosnow', width: size, height: size %>
<% elsif ski_resort.current_condition == 'pow' %>
<%=   image_tag 'powder.svg', alt: 'No snow', class: 'svg-icon-small nosnow', width: size, height: size %>
<% else %>
  <i class="fa-solid fa-circle-dot" style="color: #2d5c9e; font-size: <%= size %>"></i>
<% end %>