config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "pages#home"

  resources :ski_resorts, only: [:index, :show] do
    resources :check_ins, only: [:create]
    resources :snow_reports, only: [:create]
  end

  resources :check_ins, only: [:update] do
    resources :reviews, only: [:create]
    # resources :snow_reports, only: [:create]
    # resources :reviews, only: [:create]
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_check_in, only:[:new, :index, :create, :show]

  def index
    @reviews = @check_in.reviews
  end

  def show
    @review = @check_in.reviews.find(params[:id])
  end

  def create
    @review = Review.new(review_params)
    @review.check_in = @check_in
    if @review.save
      redirect_to ski_resort_path(@check_in.ski_resort), notice: 'Your review have submitted successfully! 🤙'
    else
      redirect_to ski_resort_path(@check_in.ski_resort)
    end
  end

  private

  def set_check_in
    @check_in = CheckIn.find(params[:check_in_id])
  end

  def review_params
    params.require(:review).permit(:lift_wait_rating, :price_rating, :crowd_rating, :food_rating, :location_rating)
  end
end

app/views/reviews/index.html.erb
<h1>Reviews for <%= @check_in.title %></h1>
<% @reviews.each do |review| %>
  <div class="review">
    <p><%= @review.lift_wait_rating %></p>
    <p><%= @review.price_rating%></p>
    <p><%= @review.crowd_rating%></p>
    <p><%= @review.food_rating%></p>
    <p><%= @review.location_rating%></p>
  </div>
<% end %>

app/views/reviews/show.html.erb
<%= link_to "View Reviews", check_in_reviews_path(@check_in) %>
<h1>Review Details</h1>
<h2><%= @review.title %></h2>
<p><%= @review.lift_wait_rating %></p>
<p><%= @review.price_rating%></p>
<p><%= @review.crowd_rating%></p>
<p><%= @review.food_rating%></p>
<p><%= @review.location_rating%></p>