config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "pages#home"

  resources :ski_resorts, only: [:index, :show] do
    resources :check_ins, only: [:create]
    resources :snow_reports, only: [:create]
  end

  resources :check_ins, only: [:update] do
    resources :reviews, only: [:create]
    # resources :snow_reports, only: [:create]
    # resources :reviews, only: [:create]
  end
end

app/models/ski_resort.rb
class SkiResort < ApplicationRecord
  serialize :courses, Hash
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  has_many :check_ins, dependent: :destroy
  has_many :reviews, through: :check_ins
  has_many :snow_reports, through: :check_ins
  has_many :users, through: :check_ins
  has_one_attached :photo

  validates :name, presence: true
  validates :location, presence: true
  validates :description, presence: true
  validates :average_rating, presence: true, inclusion: { in: 0..5 }
  validates :url, presence: true
  validates :latitude, presence: true, numericality: { greater_than_or_equal_to: -90.0, less_than_or_equal_to: 90.0 }
  validates :longitude, presence: true, numericality: { greater_than_or_equal_to: -180.0, less_than_or_equal_to: 180.0 }

  include PgSearch::Model
  pg_search_scope :search_by_name_and_location,
  against: [ :name, :location],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
         }

  def average_rating
    return 0 if reviews.nil? || reviews.empty?

    sum = 0
    reviews.each do |review|
      review_avg = (review.lift_wait_rating +
                    review.price_rating +
                    review.crowd_rating +
                    review.food_rating +
                    review.location_rating) / 5
      sum += review_avg
    end
    sum / reviews.length
  end

  def average_of(rating_type)
    return 0 if reviews.nil? || reviews.empty?

    sum = 0
    case rating_type
    when "lift_wait_rating"
      reviews.each do |review|
        sum += review.lift_wait_rating
      end
      sum / reviews.length
    when "price_rating"
      reviews.each do |review|
        sum += review.price_rating
      end
      sum / reviews.length
    when "crowd_rating"
      reviews.each do |review|
        sum += review.crowd_rating
      end
      sum / reviews.length
    when "food_rating"
      reviews.each do |review|
        sum += review.food_rating
      end
      sum / reviews.length
    when "location_rating"
      reviews.each do |review|
        sum += review.location_rating
      end
      sum / reviews.length
    end
  end

  def current_condition
    reports = snow_reports.where("DATE(snow_reports.created_at) = ?", Date.today)
    return "no_report" unless reports.present?

    reports.group(:rating).count.max_by { |condition, count| count }[0]
  end

  def current_condition_number
    conditions = %w[no_report no_snow slushy icy groomed_snow packed_powder pow]
    conditions.index(current_condition)
  end
end

app/controllers/ski_resorts_controller.rb
class SkiResortsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    if params[:query].nil? || params[:query].empty?
      @ski_resorts = SkiResort.all
    else
      @ski_resorts = SkiResort.search_by_name_and_location(params[:query])
    end
      # add additional index features in the future
    @markers = @ski_resorts.geocoded.map do |ski_resort|
      {
        lat: ski_resort.latitude,
        lng: ski_resort.longitude,
        title: ski_resort.name,
        description: ski_resort.description,
        marker_id: ski_resort.id,
        marker_html: set_marker_icon(ski_resort, (ski_resort.current_condition_number == 0) ? (ski_resort.current_condition_number + 1) * 10 : (ski_resort.current_condition_number + 0.5) * 10),
        info_window_html: render_to_string(partial: "info_window", locals: {ski_resort: ski_resort})
      }
    end
  end

  def show
    @ski_resort = SkiResort.find(params[:id])
    @check_in = CheckIn.new
    @review = Review.new
    @snow_report = SnowReport.new
    @markers =
      [{
        lat: @ski_resort.latitude,
        lng: @ski_resort.longitude,
        title: @ski_resort.name,
        description: @ski_resort.description,
        marker_id: @ski_resort.id,
        marker_html: set_marker_icon(@ski_resort, (@ski_resort.current_condition_number == 0) ? (@ski_resort.current_condition_number + 1) * 10 : (@ski_resort.current_condition_number + 0.5) * 10),
        info_window_html: render_to_string(partial: "info_window", locals: {ski_resort: @ski_resort})
      }]
    @snow_ratings = @ski_resort.snow_reports.group_by_hour(:created_at).average(:rating)
  end

  private

  def set_marker_icon(ski_resort, size)
    render_to_string(partial: "shared/snow_cond_icon", locals: {ski_resort: ski_resort, size: size})
  end
end

app/views/ski_resorts/_background_style.html.erb
<% case @ski_resort.current_condition %>
<% when 'no_snow' %>
<%= "class= bg-nosnow" %>
<% when 'slushy'%>
<%="class= bg-slush"%>
<% when 'icy'%>
<%="class= bg-icy"%>
<% when 'groomed_snow'%>
<%="class= bg-groomed"%>
<% when 'packed_powder'%>
<%="class= bg-packed"%>
<% when 'pow'%>
<%="class= bg-pow"%>
<% when ''%>
<%="class= bg-dark"%>
<% end %>

app/views/ski_resorts/_check_in_btn.html.erb
  <%# B: checks if the user has a previous check-in, from which they have not checked out %>
<% if current_user&.active_check_in %>
  <%# C: checks if the current check-in is at the ski resort the user is currently viewing %>
  <%= link_to "Check out from #{current_user.active_check_in.ski_resort.name}", ski_resort_path(current_user.active_check_in.ski_resort), class:"bby-blue-btn btn btn-secondary btn-block w-100 p-3"%>
  <%# B: No else statement %>
<% elsif user_signed_in? %>
  <%= simple_form_for([@ski_resort, @check_in], remote: true) do |f|  %>
    <%= f.submit 'Check in', class: "bby-blue-btn btn btn-secondary btn-block w-100 p-3" %>
  <% end %>
<% else %>
  <%# A: Link to sign-in page %>
  <%= link_to "Sign in", new_user_session_path, class:"bby-blue-btn btn btn-secondary btn-block w-100 p-3"%>
<% end %>

app/views/ski_resorts/_check_out_btn.html.erb
<div class="check-out-btn">
  <%= link_to "Check out", check_in_path(current_user.active_check_in), data: {turbo_method: :patch}, style: "color: white;
    text-decoration: none" %>
</div>

app/views/ski_resorts/_friends_list.html.erb
<div class="text-center mb-1 pt-2"><strong style='text-decoration: underline'>2 friends checked in!</strong></div>
<div class="profile-list">
  <% usernames = ['justdogeorge', 'snowfiend42', 'xXlil_sebastianXx', 'bruh_what', 'PrincessSparklePony', 'kostas_feet<3', 'Bill Murray', 'white_powder', 'IceLandic Cubicle', 'OhMah_OhMah_Gawd', 'my_name_is_jeff', 'Yann_was_here'] %>
  <% shuffled_usernames = usernames.shuffle %>
  <% selected_usernames = shuffled_usernames.sample(2) %>
  <% selected_usernames.each do |username| %>
    <div class="profile-item">
      <div class="profile-box" style="padding-left: 10px;">
        <%= image_tag "prof#{rand(1..12)}.jpg", alt: "profile", class: "profile-image" %>
      </div>
      <div class="username"><%= username %></div>
    </div>
  <% end %>
</div>

app/views/ski_resorts/_info_window.html.erb
<a href="<%= ski_resort_path(ski_resort) %>" class="text-decoration-none">
  <h2><%= ski_resort.name %></h2>
</a>
<div class="d-flex justify-content-start align-items-center">
  <div class="star-line">
     <% ski_resort.average_rating.times do %><i class="fa-solid fa-star" style="color: #ffdd00;"></i><% end %><% (5 - ski_resort.average_rating).times do %><i class="fa-regular fa-star" style="color: #ffdd00;"></i><% end %>
  </div>
</div>
<div class="d-flex justify-content-start align-items-center">
  <div class="dollar-sign-line">
    <p class="mb-0 ml-2">$$</p>
  </div>
</div>
<div class="current-condition-line d-flex align-items-center">
  <div class="condition-svg mr-2">
    <% if ski_resort.current_condition == 'no_snow' %>
      <%= image_tag "clear.svg", alt: "No snow", class: "svg-icon-small", width: 15, height: 15 %> NO SNOW!
    <% elsif ski_resort.current_condition == 'slushy' %>
      <%= image_tag "slush.svg", alt: "Slushy", class: "svg-icon-small", width: 15, height: 15 %> SLUSHY!
    <% elsif ski_resort.current_condition == 'icy' %>
      <%= image_tag "icy.svg", alt: "Icy", class: "svg-icon-small", width: 15, height: 15 %> ICY!
    <% elsif ski_resort.current_condition == 'groomed_snow' %>
      <%= image_tag "groomed.svg", alt: "Groomed", class: "svg-icon-small", width: 15, height: 15 %> GROOMED!
    <% elsif ski_resort.current_condition == 'packed_powder' %>
      <%= image_tag "packed.svg", alt: "Packed Powder", class: "svg-icon-small", width: 15, height: 15 %> PACKED!
    <% elsif ski_resort.current_condition == 'pow' %>
      <%= image_tag "powder.svg", alt: "Powder", class: "svg-icon-small", width: 15, height: 15 %> POW!
    <% else %>
      No reports yet today!
    <% end %>
  </div>
</div>

app/views/ski_resorts/_resort_card.html.erb
<div class="resort-card">
  <%= link_to "", ski_resort_path(ski_resort.id), style: 'position: absolute; height: 100%; width: 100%;' %>
  <h4 class="resort-name"><strong><%= ski_resort.name %></strong></h4>
  <div class="d-flex">
    <div class="info flex-column">
      <% if ski_resort.current_condition == 'no_snow' %>
        <div class="current-snow nosnow">
          <%= image_tag "clear.svg", alt: "No snow", class: "svg-icon-small" %>
          <span class="condition-text">NO SNOW!</span>
        </div>
      <% elsif ski_resort.current_condition == 'slushy' %>
        <div class="current-snow slush">
          <%= image_tag "slush.svg", alt: "Slushy", class: "svg-icon-small" %>
          <span class="condition-text">SLUSHY!</span>
        </div>
      <% elsif ski_resort.current_condition == 'icy' %>
        <div class="current-snow icy">
          <%= image_tag "icy.svg", alt: "Icy", class: "svg-icon-small" %>
          <span class="condition-text">ICY!</span>
        </div>
      <% elsif ski_resort.current_condition == 'groomed_snow' %>
        <div class="current-snow groomed">
          <%= image_tag "groomed.svg", alt: "Groomed", class: "svg-icon-small" %>
          <span class="condition-text">GROOMED!</span>
        </div>
      <% elsif ski_resort.current_condition == 'packed_powder' %>
        <div class="current-snow packed">
          <%= image_tag "packed.svg", alt: "Packed Powder", class: "svg-icon-small" %>
          <span class="condition-text">PACKED!</span>
        </div>
      <% elsif ski_resort.current_condition == 'pow' %>
        <div class="current-snow pow">
          <%= image_tag "powder.svg", alt: "Powder", class: "svg-icon-small" %>
          <span class="condition-text">POW!</span>
        </div>
      <% else %>
        <div class="current-snow no-report">
          No reports yet today!
        </div>
      <% end %>
      <div class="ratings">
        <ul class="list-unstyled">
          <li class="dif d-flex justify-content-between align-items-baseline">
            Lift waiting times
            <div>
              <%= ski_resort.average_of("lift_wait_rating") %>
              <i class="fa-solid fa-star" style="color: #2d5c9e;"></i>
            </div>
          </li>
          <li class="dif d-flex justify-content-between align-items-baseline">
            Food
            <div>
              <%= ski_resort.average_of("food_rating") %>
              <i class="fa-solid fa-star" style="color: #2d5c9e;"></i>
            </div>
          </li>
          <li class="dif d-flex justify-content-between align-items-baseline">
            Crowded?
            <div>
              <%= ski_resort.average_of("crowd_rating") %>
              <i class="fa-solid fa-star" style="color: #2d5c9e;"></i>
            </div>
          </li>
          <li class="dif d-flex justify-content-between align-items-baseline">
            Location
            <div>
              <%= ski_resort.average_of("location_rating") %>
              <i class="fa-solid fa-star" style="color: #2d5c9e;"></i>
            </div>
          </li>
          <li class="dif d-flex justify-content-between align-items-baseline">
            Overall price
            <div>
              <%= ski_resort.average_of("price_rating") %>
              <i class="fa-solid fa-star" style="color: #2d5c9e;"></i>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <div class="image">
      <% if ski_resort.photo.attached? %>
        <%= cl_image_tag ski_resort.photo.key, class: "image" %>
      <% else %>
        <%= image_tag "ski_resort.jpg", class: "image" %>
      <% end %>
    </div>
  </div>
</div>

app/views/ski_resorts/_review_btn.html.erb
<div class='review-btn'>
  <button type="button" class="btn p-3 w-100 h-100"  data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Leave your review
  </button>
</div>

app/views/ski_resorts/_review_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header primary">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Slide and rate your review here!</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-rate-body grid" >
        <%= simple_form_for([check_in, review], remote: true, html: {class: "review-form"}) do |form| %>
          <div class="row">
            <div class="col-6">
              <div class="rate" data-controller="rating">
                <div class="emoji" data-rating-target="emoji">😑</div>
                <%= form.input :lift_wait_rating, as: :range,  input_html: {data: {action: "change->rating#changeEmoji"}, min:"1", max:"5", step:"1"}, class:"form-range" %>
              </div>
            </div>
            <div class="col-6">
              <div class="rate" data-controller="rating">
                <div class="emoji" data-rating-target="emoji">😑</div>
                <%= form.input :price_rating, as: :range,  input_html: {data: {action: "change->rating#changeEmoji"}, min:"1", max:"5", step:"1"}, class:"form-range" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-6">
              <div class="rate" data-controller="rating">
                <div class="emoji" data-rating-target="emoji">😑</div>
                <%= form.input :crowd_rating, as: :range,  input_html: {data: {action: "change->rating#changeEmoji"}, min:"1", max:"5", step:"1"}, class:"form-range" %>
              </div>
            </div>
            <div class="col-6">
              <div class="rate" data-controller="rating">
                <div class="emoji" data-rating-target="emoji">😑</div>
                <%= form.input :food_rating, as: :range,  input_html: {data: {action: "change->rating#changeEmoji"}, min:"1", max:"5", step:"1"}, class:"form-range" %>
              </div>
            </div>
          </div>
          <div class="rate" data-controller="rating">
            <div class="emoji" data-rating-target="emoji">😑</div>
            <%= form.input :location_rating, as: :range,  input_html: {data: {action: "change->rating#changeEmoji"}, min:"1", max:"5", step:"1"}, class:"form-range" %>
          </div>
          <div class="modal-footer">
            <%= form.submit 'Submit Your Review' %>
            <button type="button" class="btn btn-info" data-bs-dismiss="modal">Close</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/ski_resorts/_snow_guide.html.erb
<%# snow descriptions %>
<div class="border-top py-2 mb-4">

  <h1 class="text-center">Snow Guide</h1>
  <div class="mb-4 px-2">
    <h2>Powder Snow</h2>
      <%= image_tag "powder snow.avif", class: "mx-auto d-block img-fluid rounded" %>
    <p>Powder snow, or "pow" for short, is freshly fallen, light, dry, and fluffy snow. It's the holy grail among skiers and snowboarders for its soft and smooth texture. Excellent for floatation and the feeling of gliding on top of the snow.</p>
  <h2>Packed Powder</h2>
    <%= image_tag "packed_snow.jpg", class: "mx-auto d-block img-fluid rounded" %>

  <p>Packed powder is snow that has been compacted from the pressure of skiers and riders. It offers a good balance between softness and stability, making it suitable for carving turns and maintaining control.</p>
  <h2>Groomed Snow</h2>
    <%= image_tag "groomed.avif", class: "mx-auto d-block img-fluid rounded" %>

  <p>Groomed snow happens when the resort's grooming machines flatten and smooth the snow surface. It provides a consistent and even surface, making it easier for skiers and snowboarders to control their movements. Groomed runs are popular for carving and practicing technique.</p>
  <h2>Icy</h2>
    <%= image_tag "icy.avif", class: "mx-auto d-block img-fluid rounded" %>

  <p>Icy conditions occur when the snow freezes and becomes hard, creating a slippery surface. Icy slopes can be challenging to navigate and require precise control and edge grip to maintain stability and control.</p>
  <h2>Slushy</h2>
    <%= image_tag "slush snow.jpg", class: "mx-auto d-block img-fluid rounded" %>

  <p>Slushy or wet snow occurs as temperatures rise, causing the snow to melt and become wet. It can create heavy, sticky conditions that are more difficult to maneuver through. Slushy snow tends to be slower and requires adjustments in technique.</p>
  <h2>No Snow</h2>
    <%= image_tag "no snow.avif", class: "mx-auto d-block img-fluid rounded" %>

  <p>No snow is a no-go! Stay home or hit the hot spring instead.
  </div>
</div>

app/views/ski_resorts/_snow_guide_button.html.erb
<div class='d-flex p-3' style='position: absolute; width: 100%; z-index: 2; margin-top: 40px; left: 10px;'>
  <div class="info-button">
    <button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#snowGuideModal">
      <i class="fas fa-info-circle"></i>
    </button>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="snowGuideModal" tabindex="-1" aria-labelledby="snowGuideModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <h1 class="text-center">Snow Guide</h1>

<div class="info">
  <table class="table table-bordered">
    <tr>
      <td class="text-center">
        <div class="current-snow nosnow">
          <%= image_tag "clear.svg", alt: "No snow", class: "svg-icon-small" %>
          <br>
          <span class="condition-text">NO SNOW!</span>
        </div>
      </td>
      <td class="text-center">
        <div class="current-snow slush">
          <%= image_tag "slush.svg", alt: "Slushy", class: "svg-icon-small" %>
          <span class="condition-text">SLUSHY!</span>
        </div>
      </td>
      <td class="text-center">
        <div class="current-snow icy">
          <%= image_tag "icy.svg", alt: "Icy", class: "svg-icon-small", height: "43px" %>
          <span class="condition-text">ICY!</span>
        </div>
      </td>
    </tr>
    <tr>
      <td class="text-center">
        <div class="current-snow groomed">
          <%= image_tag "groomed.svg", alt: "Groomed", class: "svg-icon-small" %>
          <span class="condition-text">GROOMED!</span>
        </div>
      </td>
      <td class="text-center">
        <div class="current-snow packed">
          <%= image_tag "packed.svg", alt: "Packed Powder", class: "svg-icon-small" %>
          <span class="condition-text">PACKED!</span>
        </div>
      </td>
      <td class="text-center">
        <div class="current-snow pow">
          <%= image_tag "powder.svg", alt: "Powder", class: "svg-icon-small" %>
          <span class="condition-text">POW!</span>
        </div>
      </td>
    </tr>
  </table>
</div>

        <div class="mb-4 px-2">
          <h2>Powder Snow</h2>
          <%= image_tag "powder snow.avif", class: "mx-auto d-block img-fluid rounded" %>
          <p>Powder snow, or "pow" for short, is freshly fallen, light, dry, and fluffy snow. It's the holy grail among skiers and snowboarders for its soft and smooth texture. Excellent for floatation and the feeling of gliding on top of the snow.</p>
          <h2>Packed Powder</h2>
          <%= image_tag "packed_snow.jpg", class: "mx-auto d-block img-fluid rounded" %>
          <p>Packed powder is snow that has been compacted from the pressure of skiers and riders. It offers a good balance between softness and stability, making it suitable for carving turns and maintaining control.</p>
          <h2>Groomed Snow</h2>
          <%= image_tag "groomed.avif", class: "mx-auto d-block img-fluid rounded" %>
          <p>Groomed snow happens when the resort's grooming machines flatten and smooth the snow surface. It provides a consistent and even surface, making it easier for skiers and snowboarders to control their movements. Groomed runs are popular for carving and practicing technique.</p>
          <h2>Icy</h2>
          <%= image_tag "icy.avif", class: "mx-auto d-block img-fluid rounded" %>
          <p>Icy conditions occur when the snow freezes and becomes hard, creating a slippery surface. Icy slopes can be challenging to navigate and require precise control and edge grip to maintain stability and control.</p>
          <h2>Slushy</h2>
          <%= image_tag "slush snow.jpg", class: "mx-auto d-block img-fluid rounded" %>
          <p>Slushy or wet snow occurs as temperatures rise, causing the snow to melt and become wet. It can create heavy, sticky conditions that are more difficult to maneuver through. Slushy snow tends to be slower and requires adjustments in technique.</p>
          <h2>No Snow</h2>
          <%= image_tag "no snow.avif", class: "mx-auto d-block img-fluid rounded" %>
          <p>No snow is a no-go! Stay home or hit the hot spring instead.
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

app/views/ski_resorts/_snow_guide_modal.html.erb
<%# snow descriptions %>
<div class="border-top py-2 mb-4">

  <h1 class="text-center">Snow Guide</h1>
  <div class="mb-4 px-2">
    <h2>Powder Snow</h2>
      <%= image_tag "powder snow.avif", class: "mx-auto d-block img-fluid rounded" %>
    <p>Powder snow, or "pow" for short, is freshly fallen, light, dry, and fluffy snow. It's the holy grail among skiers and snowboarders for its soft and smooth texture. Excellent for floatation and the feeling of gliding on top of the snow.</p>
  <h2>Packed Powder</h2>
    <%= image_tag "packed_snow.jpg", class: "mx-auto d-block img-fluid rounded" %>

  <p>Packed powder is snow that has been compacted from the pressure of skiers and riders. It offers a good balance between softness and stability, making it suitable for carving turns and maintaining control.</p>
  <h2>Groomed Snow</h2>
    <%= image_tag "groomed.avif", class: "mx-auto d-block img-fluid rounded" %>

  <p>Groomed snow happens when the resort's grooming machines flatten and smooth the snow surface. It provides a consistent and even surface, making it easier for skiers and snowboarders to control their movements. Groomed runs are popular for carving and practicing technique.</p>
  <h2>Icy</h2>
    <%= image_tag "icy.avif", class: "mx-auto d-block img-fluid rounded" %>

  <p>Icy conditions occur when the snow freezes and becomes hard, creating a slippery surface. Icy slopes can be challenging to navigate and require precise control and edge grip to maintain stability and control.</p>
  <h2>Slushy</h2>
    <%= image_tag "slush snow.jpg", class: "mx-auto d-block img-fluid rounded" %>

  <p>Slushy or wet snow occurs as temperatures rise, causing the snow to melt and become wet. It can create heavy, sticky conditions that are more difficult to maneuver through. Slushy snow tends to be slower and requires adjustments in technique.</p>
  <h2>No Snow</h2>
    <%= image_tag "no snow.avif", class: "mx-auto d-block img-fluid rounded" %>

  <p>No snow is a no-go! Stay home or hit the hot spring instead.
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <h1 class="text-center">Snow Guide</h1>
  <div class="mb-4 px-2">
    <h2>Powder Snow</h2>
      <%= image_tag "powder snow.avif", class: "mx-auto d-block img-fluid rounded" %>
    <p>Powder snow, or "pow" for short, is freshly fallen, light, dry, and fluffy snow. It's the holy grail among skiers and snowboarders for its soft and smooth texture. Excellent for floatation and the feeling of gliding on top of the snow.</p>
  <h2>Packed Powder</h2>
    <%= image_tag "packed_snow.jpg", class: "mx-auto d-block img-fluid rounded" %>

  <p>Packed powder is snow that has been compacted from the pressure of skiers and riders. It offers a good balance between softness and stability, making it suitable for carving turns and maintaining control.</p>
  <h2>Groomed Snow</h2>
    <%= image_tag "groomed.avif", class: "mx-auto d-block img-fluid rounded" %>

  <p>Groomed snow happens when the resort's grooming machines flatten and smooth the snow surface. It provides a consistent and even surface, making it easier for skiers and snowboarders to control their movements. Groomed runs are popular for carving and practicing technique.</p>
  <h2>Icy</h2>
    <%= image_tag "icy.avif", class: "mx-auto d-block img-fluid rounded" %>

  <p>Icy conditions occur when the snow freezes and becomes hard, creating a slippery surface. Icy slopes can be challenging to navigate and require precise control and edge grip to maintain stability and control.</p>
  <h2>Slushy</h2>
    <%= image_tag "slush snow.jpg", class: "mx-auto d-block img-fluid rounded" %>

  <p>Slushy or wet snow occurs as temperatures rise, causing the snow to melt and become wet. It can create heavy, sticky conditions that are more difficult to maneuver through. Slushy snow tends to be slower and requires adjustments in technique.</p>
  <h2>No Snow</h2>
    <%= image_tag "no snow.avif", class: "mx-auto d-block img-fluid rounded" %>

  <p>No snow is a no-go! Stay home or hit the hot spring instead.
  </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/ski_resorts/_specific_info.html.erb
<div class="info text-light">
  <div class="caracteristiques d-flex justify-content-around">
    <div class="d-flex flex-column">
      <p class="mb-1 mt-2">Length</p>
      <p><strong><%= @ski_resort.length.round(2)%>km</strong></p>
    </div>
    <div class="d-flex flex-column">
      <p class="mb-1 mt-2">Elevation</p>
      <p><strong><%= @ski_resort.height.round(2)%>m</strong></p>
    </div>
    <div class="d-flex flex-column">
      <p class="mb-1 mt-2">Temp</p>
      <p><strong><%= @ski_resort.temp.round(1)%>º</strong></p>
    </div>
  </div>
  <div class="friends">
  </div>
</div>